export const MAP_DATA_LOAD_REQUEST = 'MAP_DATA_LOAD_REQUEST';
export const MAP_DATA_LOAD_REQUEST_SUCCESS = 'MAP_DATA_LOAD_REQUEST_SUCCESS';
export const MAP_DATA_LOAD_REQUEST_FAILURE = 'MAP_DATA_LOAD_REQUEST_FAILURE';
