export const MAP_DATA_LOAD_REQUEST = 'MAP_DATA_LOAD_REQUEST';
export const MAP_DATA_LOAD_REQUEST_SUCCESS = 'MAP_DATA_LOAD_REQUEST_SUCCESS';
export const MAP_DATA_LOAD_REQUEST_FAILURE = 'MAP_DATA_LOAD_REQUEST_FAILURE';

export const MAP_DATA_LOAD_ALL_ITEMS = 'MAP_DATA_LOAD_ALL_ITEMS';
export const MAP_DATA_LOAD_ALL_ITEMS_SUCCESS = 'MAP_DATA_LOAD_ALL_ITEMS_SUCCESS';
export const MAP_DATA_LOAD_ALL_ITEMS_FAILURE = 'MAP_DATA_LOAD_ALL_ITEMS_FAILURE';

export const MAP_DATA_LOAD_ALL_LOCATIONS = 'MAP_DATA_LOAD_ALL_LOCATIONS';
export const MAP_DATA_LOAD_ALL_LOCATIONS_SUCCESS = 'MAP_DATA_LOAD_ALL_LOCATIONS_SUCCESS';
export const MAP_DATA_LOAD_ALL_LOCATIONS_FAILURE = 'MAP_DATA_LOAD_ALL_LOCATIONS_FAILURE';
