export const SEARCH_ITEMS_LOAD_REQUEST = 'SEARCH_ITEMS_LOAD_REQUEST';
export const SEARCH_ITEMS_LOAD_REQUEST_SUCCESS = 'SEARCH_ITEMS_LOAD_REQUEST_SUCCESS';
export const SEARCH_ITEMS_LOAD_REQUEST_FAILURE = 'SEARCH_ITEMS_LOAD_REQUEST_FAILURE';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
